/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.reserva.telas;

import java.net.URL;
import javax.help.HelpBroker;
import javax.help.HelpSet;

/**
 *
 * @author pablicio
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setExtendedState(Menu.MAXIMIZED_BOTH);
        this.setTitle("Sistema de Reserva de Quartos e Gestão de Vendas - Hotel Chateubriand");

    }
    private HelpSet hs;
    private HelpBroker hb;
    private URL hsURL;
    
    
    
    public void openHelp(){
        String pathToHS = "/appwithhelp/docs/appwithhelp-hs.xml";
        try {
            hsURL = getClass().getResource(pathToHS);
            System.out.println(hsURL);
            hs = new HelpSet(null,hsURL);
        } catch (Exception e) {
            System.out.println("HelpSet"+e.getMessage());
            System.out.println("HelpSet"+ pathToHS + " não encontrado");

        }
        hb = hs.createHelpBroker();
        hb.setDisplayed(true);
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        lAcesso = new javax.swing.JLabel();
        lPessoa = new javax.swing.JLabel();
        lNome = new javax.swing.JLabel();
        lPai = new javax.swing.JLabel();
        lMae = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        menuArquivo = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuConfiguracoes = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(204, 255, 255));

        lAcesso.setText("lAcesso");
        desktopPane.add(lAcesso);
        lAcesso.setBounds(30, 120, 0, 14);

        lPessoa.setText("lPessoa");
        desktopPane.add(lPessoa);
        lPessoa.setBounds(30, 40, 0, 14);

        lNome.setText("lNome");
        desktopPane.add(lNome);
        lNome.setBounds(30, 60, 0, 14);

        lPai.setText("lPai");
        desktopPane.add(lPai);
        lPai.setBounds(30, 80, 0, 20);

        lMae.setText("lMae");
        desktopPane.add(lMae);
        lMae.setBounds(30, 100, 0, 14);

        menuBar.setBackground(new java.awt.Color(194, 206, 241));

        fileMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/reserva/imagens/Inicio.png"))); // NOI18N
        fileMenu.setMnemonic('f');
        fileMenu.setText("SisReserva");
        menuBar.add(fileMenu);

        menuArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/reserva/imagens/Archivo.png"))); // NOI18N
        menuArquivo.setMnemonic('e');
        menuArquivo.setText("Arquivo");

        cutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/reserva/imagens/habitaciones.png"))); // NOI18N
        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Quartos");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        menuArquivo.add(cutMenuItem);

        copyMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/reserva/imagens/productos.png"))); // NOI18N
        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Produtos");
        copyMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyMenuItemActionPerformed(evt);
            }
        });
        menuArquivo.add(copyMenuItem);

        menuBar.add(menuArquivo);

        helpMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/reserva/imagens/Reservas.png"))); // NOI18N
        helpMenu.setMnemonic('h');
        helpMenu.setText("Reservas");

        contentMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/reserva/imagens/reservas-consumos.png"))); // NOI18N
        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Reservas e Consumos");
        contentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/reserva/imagens/clientes.png"))); // NOI18N
        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Clientes");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/reserva/imagens/pagos.png"))); // NOI18N
        jMenuItem4.setText("Pagamentos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        helpMenu.add(jMenuItem4);

        menuBar.add(helpMenu);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/reserva/imagens/Consultas.png"))); // NOI18N
        jMenu1.setText("Consultas");
        menuBar.add(jMenu1);

        menuConfiguracoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/reserva/imagens/Configuraciones.png"))); // NOI18N
        menuConfiguracoes.setText("Configurações");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/reserva/imagens/trabajadores.png"))); // NOI18N
        jMenuItem1.setText("Usuários e Acessos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuConfiguracoes.add(jMenuItem1);

        menuBar.add(menuConfiguracoes);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/reserva/imagens/Herramientas.png"))); // NOI18N
        jMenu3.setText("Ferramentas");
        menuBar.add(jMenu3);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/reserva/imagens/Ayuda.png"))); // NOI18N
        jMenu5.setText("Ajuda");

        jMenuItem2.setText("Sobre o Sistema");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuItem3.setText("Ajuda");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        menuBar.add(jMenu5);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/reserva/imagens/Salir.png"))); // NOI18N
        jMenu4.setText("Sair");
        menuBar.add(jMenu4);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 841, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
        // TODO add your handling code here:
        Habitacao form =new Habitacao();
        desktopPane.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void copyMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyMenuItemActionPerformed
        // TODO add your handling code here:
        Produto form =new Produto();
        desktopPane.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_copyMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        // TODO add your handling code here:
        Cliente form =new Cliente();
        desktopPane.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Funcionario form =new Funcionario();
        desktopPane.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void contentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItemActionPerformed
        // TODO add your handling code here:
          Reserva form = new Reserva();
        desktopPane.add(form);
        form.toFront();
        form.setVisible(true);
        Reserva.tCodFuncionario.setText(lPessoa.getText());
        Reserva.tFuncionario.setText(lNome.getText() + " " + lPai.getText());
        Reserva.idusuario=Integer.parseInt(lPessoa.getText());
    }//GEN-LAST:event_contentMenuItemActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        openHelp();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    public static javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    public static javax.swing.JLabel lAcesso;
    public static javax.swing.JLabel lMae;
    public static javax.swing.JLabel lNome;
    public static javax.swing.JLabel lPai;
    public static javax.swing.JLabel lPessoa;
    public static javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuBar menuBar;
    public static javax.swing.JMenu menuConfiguracoes;
    // End of variables declaration//GEN-END:variables

}
